services:
  mosquitto:
    restart: unless-stopped
    image: eclipse-mosquitto
    volumes:
      - /etc/owntracks/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001    
  meshtastic-bridge:
    restart: unless-stopped
    build:
      context: /etc/owntracks/meshtastic-bridge
      dockerfile: Dockerfile
    volumes:
      - /etc/owntracks/config.yaml:/code/config.yaml
  owntracks-recorder:
    restart: unless-stopped
    image: owntracks/recorder
    volumes:
      - /etc/owntracks/store:/store
    ports:
      - 8083:8083
    environment:
      - OTR_HOST=10.0.1.5
  owntracks-frontend:
    restart: unless-stopped
    image: owntracks/frontend
    ports:
      - 8084:80
    environment:
      - SERVER_HOST=10.0.1.5
      - SERVER_PORT=8083
