services:
  mosquitto:
    restart: unless-stopped
    image: eclipse-mosquitto
    volumes:
      - /etc/owntracks-meshtastic/mosquitto:/mosquitto/config
    ports:
      - 1883:1883
      - 9001:9001
  meshtastic-bridge:
    restart: unless-stopped
    build:
      context: /etc/owntracks-meshtastic/meshtastic-bridge
      dockerfile: Dockerfile
    volumes:
      - /etc/owntracks-meshtastic/config.yaml:/code/config.yaml
  owntracks-recorder:
    restart: unless-stopped
    image: owntracks/recorder
    volumes:
      - /etc/owntracks-meshtastic/store:/store
    ports:
      - 8083:8083
    environment:
      - OTR_HOST=CHANGEME
  owntracks-frontend:
    restart: unless-stopped
    image: owntracks/frontend
    ports:
      - 8084:80
    environment:
      - SERVER_HOST=CHANGEME
      - SERVER_PORT=8083
